### ISSUE TITLE
xtensor required version undocumented

### ISSUE THREAD

**Issue by KrisThielemans** [microsoft/yardl#75]
For whatever reason, my conda install got xtensor=0.21.10. The generated code fails to compile though as it `xtensor_container` doesn't have the `flat` member. https://github.com/xtensor-stack/xtensor/commit/50e3d42c4316ff01c12d3e039db567b42f009772 says this means at least 0.23.10 is required.

Ideally, this minimum version should be added to the generated `CMakeLists.txt`.

Of course, the same holds for other dependencies.

**Comment by johnstairs** [comment]
Thanks for the feedback. Fixed now.
