### ISSUE TITLE
yardl version not yet defined or set during build

### ISSUE THREAD

**Issue by naegelejd** [microsoft/yardl#76]
Soon we'll need to actually version `yardl`, which may include:

- Defining version in the repo
- Configuring build to set version/commit in `cmd/yardl.go`
- Tag and release

https://github.com/microsoft/yardl/blob/76ea21d383fd8979dff584ae3b7de10f3e340453/tooling/cmd/yardl/main.go#L10-L13

**Comment by johnstairs** [comment]
@naegelejd, I'm sure we can improve the process, but we we tag and release, and set the version on the binary. 

```
$ wget -q https://github.com/microsoft/yardl/releases/download/v0.3.0/yardl_0.3.0_linux_x86_64.tar.gz

$ tar -xvf yardl_0.3.0_linux_x86_64.tar.gz 
LICENSE
NOTICE.txt
yardl

$ ./yardl --version
yardl version 0.3.0 commit b9465f513d149ba699da8531b65e3d786202d229
```

**Comment by naegelejd** [comment]
Got it. This is done automatically by `goreleaser` in the Github CI workflow
https://github.com/microsoft/yardl/blob/76ea21d383fd8979dff584ae3b7de10f3e340453/.github/workflows/ci.yml#L199
https://github.com/microsoft/yardl/blob/76ea21d383fd8979dff584ae3b7de10f3e340453/.github/workflows/ci.yml#L220-L224
Doing this locally at build time is not a priority, so... closing.
